name = "Hugo Bulma Blocks Theme"
description = "A Bulma Based Blocks Theme"
license = "MIT"
source_repo = "https://github.com/qgis/QGIS-Hugo-Website-Theme"
tags = ["website", "bulma", "blocks"]
min_version = 0.14

[author]
    name = "Tim Sutton"
    twitter = "http://twitter.com/timlinux"
    url = "http://github.com/timlinux"

